add_newline = true

# ----------------------------------------------------
# format
# ----------------------------------------------------
format = """
$directory\
$git_branch\
$git_status\
$direnv\
$python\
$fill\
$cmd_duration\
$time\
\n$character\
"""

# Enable if it appears on the same line as the command
# right_format = """
# $cmd_duration\
# $time\
# """

# ----------------------------------------------------
# left module
# ----------------------------------------------------
[python]
format = """
[](fg:#957FB8)\
[$virtualenv]($style)\
[](fg:#957FB8)\
"""
style = "bold fg:#1F1F28 bg:#957FB8"

[fill]
symbol = '─'

[directory]
truncation_length = 6
truncation_symbol = ' '
home_symbol = '~'
read_only = ' 󰌾 '

format = """
[](fg:#7E9CD8)\
[$path]($style)\
[$read_only]($read_only_style)\
[](fg:#7E9CD8)\
"""

before_repo_root_style = 'bold fg:#1F1F28 bg:#7E9CD8'
repo_root_style = 'bold fg:#1F1F28 bg:#7E9CD8'
repo_root_format = """
[](fg:#7E9CD8)\
[󰊢 /]($repo_root_style)[$repo_root]($repo_root_style)[$path]($style)\
[$read_only]($read_only_style)\
[](fg:#7E9CD8)\
"""

style = 'bold fg:#1F1F28 bg:#7E9CD8'
read_only_style = 'bold fg:#1F1F28 bg:#7E9CD8'

[direnv]
disabled = false
format = """
[](fg:#7FB4CA)\
[$symbol$allowed]($style)\
[](fg:#7FB4CA)\
"""
style = "bold fg:#1F1F28 bg:#7FB4CA"

[git_branch]
symbol = ""
style = "fg:#98BB6C bg:#223249"
format = """
[](fg:#223249)\
[$symbol $branch]($style)\
"""

[git_status]
style = "fg:#98BB6C bg:#223249"
format = """
[$all_status$ahead_behind]($style)\
[](fg:#223249)\
"""

# ----------------------------------------------------
# right module
# ----------------------------------------------------
[cmd_duration]
min_time = 1
style = 'fg:#E6C384'
format = "[ $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[  $time](fg:#DCD7BA)]($style)'

# ----------------------------------------------------
# prompt module
# ----------------------------------------------------
[character]
vimcmd_symbol = '[V](bold green) '
